### ISSUE TITLE
nzpy 1.1. runtime error using example1 in documentation

### ISSUE THREAD

**Issue by stelin1960** [IBM/nzpy#25]
I have installed nzpy 1.1 and python3.5. Running the first example in the documentation (db1 --> SYSTEM) I get:

[root@localhost NzPy]# python3.5 sample1.py
ERROR:  CREATE TABLE: object "CUSTOMERADDRESS" already exists.

1 rows inserted
1 rows inserted
1 rows inserted
Traceback (most recent call last):
  File "sample1.py", line 26, in <module>
    cursor.execute("select * from customerAddress where Id = ? and Name = ?", (1,'Jack'))
  File "/usr/local/lib/python3.5/site-packages/nzpy-1.11-py3.5.egg/nzpy/core.py", line 842, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib/python3.5/site-packages/nzpy-1.11-py3.5.egg/nzpy/core.py", line 1775, in execute
    query = self.Prepare(cursor, query, vals)
  File "/usr/local/lib/python3.5/site-packages/nzpy-1.11-py3.5.egg/nzpy/core.py", line 1762, in Prepare
    self.execute(cursor, statement, None)
  File "/usr/local/lib/python3.5/site-packages/nzpy-1.11-py3.5.egg/nzpy/core.py", line 1803, in execute
    raise ProgrammingError(self.error)
nzpy.core.ProgrammingError: ERROR:  ANALYZE is supported only with ODBC, JDBC, OLE-DB, GOLANG Prepared Statements

Do I have to install any of the protocols given above?

**Comment by stelin1960** [comment]
The above section shows that the table already exists. This also happens w/o already existing table:
Table customerAddress created successfully
1 rows inserted
1 rows inserted
1 rows inserted
Traceback (most recent call last):
  File "sample1.py", line 26, in <module>
    cursor.execute("select * from customerAddress where Id = ? and Name = ?", (1,'Jack'))
  File "/usr/local/lib/python3.5/site-packages/nzpy-1.11-py3.5.egg/nzpy/core.py", line 842, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib/python3.5/site-packages/nzpy-1.11-py3.5.egg/nzpy/core.py", line 1775, in execute
    query = self.Prepare(cursor, query, vals)
  File "/usr/local/lib/python3.5/site-packages/nzpy-1.11-py3.5.egg/nzpy/core.py", line 1762, in Prepare
    self.execute(cursor, statement, None)
  File "/usr/local/lib/python3.5/site-packages/nzpy-1.11-py3.5.egg/nzpy/core.py", line 1803, in execute
    raise ProgrammingError(self.error)
nzpy.core.ProgrammingError: ERROR:  ANALYZE is supported only with ODBC, JDBC, OLE-DB, GOLANG Prepared Statements

**Comment by shabbir10july** [comment]
@stelin1960 The error doesn't have to do anything with customerAddress table. The error is because your NPS is at older version and it doesn't support nzpy (Netezza python driver).

**Comment by stelin1960** [comment]
That means nzpy is supported running 11.1.x.y and later?

**Comment by shabbir10july** [comment]
It is supported with NPS 11.1.2.x and later

**Comment by joebeeson** [comment]
Perhaps a warning could be raised during connection to let the user know?

**Comment by shabbir10july** [comment]
It is not possible to return warning from code for such case. 
However, I have updated README.md mentioning that nzpy works with NPS 11.1.2.x and later.
